/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasexpertos;

import datosPerro.Perro;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author j_vgo
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    private Perro akita = new Perro("Akita", true, true, true, true, "/img/Akita-2-100x100.png");
    private Perro boxer = new Perro("Boxer", false, true, true, false, "/img/Boxer-03-100x100.png");
    private Perro bichon = new Perro("Bichon-Frise", false, false, false, false, "/img/bichon_frise-100x100.png");
    private Perro border = new Perro("Border-Collie", true, false, true, true, "/img/border-collie-100x100.png");
    private Perro dalmata = new Perro("Dalmata", false, true, true, true, "/img/dalmata-100x100.png");

    private Perro atual;
    private Perro inicio;

    public Tela() {
        initComponents();
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/dog.png")).getImage());
        setTitle("Sistema Experro");
        jP_Comandos.setBorder(BorderFactory.createTitledBorder("Comandos"));
        Info.setEditable(false);
        jP_Apresentacao.setBorder(BorderFactory.createTitledBorder("Perros"));

        cargar();
        actualizarInformacion(akita);
        atual = akita;
    }

    public void cargar() {
        akita.setSeguiente(boxer);

        boxer.setAnterior(akita);
        boxer.setSeguiente(bichon);

        bichon.setAnterior(boxer);
        bichon.setSeguiente(border);

        border.setAnterior(bichon);
        border.setSeguiente(dalmata);

        dalmata.setAnterior(border);
        inicio = akita;

    }

    public void actualizarInformacion(Perro p) {
        if (p != null) {
            Info.setText("");
            lblImagen.setIcon(new ImageIcon(getClass().getResource(p.getRutaImagen())));
            lblNome.setText(p.getNome());
            String t = "";
            if (p.isCazador()) {
                t = t + "Es Cazador \n";
            } else {
                t = t + "No es Cazador \n";
            }
            if (p.isGrande()) {
                t = t + "Es Grande \n";
            } else {
                t = t + "No es Grande \n";
            }
            if (p.isPeloLargo()) {
                t = t + "Tiene Pelos Largos \n";
            } else {
                t = t + "No tiene pelos largos \n";
            }
            if (p.isDeportivo()) {
                t = t + "Es Deportivo \n";
            } else {
                t = t + "No es Deportivo \n";
            }
            Info.setText(t);
        } else {
            lblImagen.setIcon(new ImageIcon(""));
            lblNome.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Comandos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jB_Preguntas = new javax.swing.JButton();
        jP_Apresentacao = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextPane();
        Anterior = new javax.swing.JButton();
        Seguiente = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel1.setText("¿Puedo adivinar qué perro está imaginando?");

        jB_Preguntas.setText("Preguntas");
        jB_Preguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PreguntasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_ComandosLayout = new javax.swing.GroupLayout(jP_Comandos);
        jP_Comandos.setLayout(jP_ComandosLayout);
        jP_ComandosLayout.setHorizontalGroup(
            jP_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ComandosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_Preguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_ComandosLayout.setVerticalGroup(
            jP_ComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ComandosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Preguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblNome.setText("jLabel2");

        jScrollPane1.setViewportView(Info);

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Seguiente.setText("Seguiente");
        Seguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_ApresentacaoLayout = new javax.swing.GroupLayout(jP_Apresentacao);
        jP_Apresentacao.setLayout(jP_ApresentacaoLayout);
        jP_ApresentacaoLayout.setHorizontalGroup(
            jP_ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ApresentacaoLayout.createSequentialGroup()
                .addGroup(jP_ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ApresentacaoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblNome))
                    .addGroup(jP_ApresentacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Anterior)
                        .addGap(18, 18, 18)
                        .addComponent(Seguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_ApresentacaoLayout.setVerticalGroup(
            jP_ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ApresentacaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNome)
                .addGap(52, 52, 52)
                .addGroup(jP_ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_ApresentacaoLayout.createSequentialGroup()
                        .addGroup(jP_ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Anterior)
                            .addComponent(Seguiente))
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jP_Comandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jP_Apresentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jP_Apresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jP_Comandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_PreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PreguntasActionPerformed
        // TODO add your handling code here:
        inicio = akita;
        Perro aux = akita;
        int p = 0;
        int res = JOptionPane.showConfirmDialog(rootPane, "¿Tiene Pelo Largos", null, JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            do {
                if (inicio.isPeloLargo()) {
                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Cazador?", null, JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        do {
                            if (aux.isCazador() && aux.isPeloLargo()) {
                                p++;
                            }
                            aux = aux.getSeguiente();
                        } while (aux != null);
                        aux = akita;
                        if (p == 0) {
                            JOptionPane.showMessageDialog(rootPane, "No existe");
                            System.exit(0);
                        }
                        if (p != 0) {
                            p = 0;
                            res = JOptionPane.showConfirmDialog(rootPane, "¿Es Grande?", null, JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                do {
                                    if (aux.isCazador() && aux.isPeloLargo() && aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (aux.isCazador() && aux.isPeloLargo() && aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (aux.isCazador() && aux.isPeloLargo() && aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            } else {//else não é grande
                                do {
                                    if (aux.isCazador() && aux.isPeloLargo() && !aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (aux.isCazador() && aux.isPeloLargo() && !aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (aux.isCazador() && aux.isPeloLargo() && !aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            }
                        }
                    } else {// else não é caçador
                        do {
                            if (!aux.isCazador() && aux.isPeloLargo()) {
                                p++;
                            }
                            aux = aux.getSeguiente();
                        } while (aux != null);
                        aux = akita;
                        if (p == 0) {
                            JOptionPane.showMessageDialog(rootPane, "No existe");
                            System.exit(0);
                        }
                        if (p != 0) {
                            p = 0;
                            res = JOptionPane.showConfirmDialog(rootPane, "¿Es Grande?", null, JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                do {
                                    if (!aux.isCazador() && aux.isPeloLargo() && aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (!aux.isCazador() && aux.isPeloLargo() && aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (!aux.isCazador() && aux.isPeloLargo() && aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            } else {//else não é grande
                                do {
                                    if (!aux.isCazador() && aux.isPeloLargo() && !aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (!aux.isCazador() && aux.isPeloLargo() && !aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (!aux.isCazador() && aux.isPeloLargo() && !aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                inicio = inicio.getSeguiente();
            } while (inicio != null);
        } else if(res == 1) {//else não tem pelo largo
            do {
                System.out.println("teste");
                if (!inicio.isPeloLargo()) {
                    System.out.println("teste22");
                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Cazador?", null, JOptionPane.YES_NO_OPTION);
                    if (res == 0) {
                        do {
                            if (aux.isCazador() && !aux.isPeloLargo()) {
                                p++;
                            }
                            aux = aux.getSeguiente();
                        } while (aux != null);
                        aux = akita;
                        if (p == 0) {
                            JOptionPane.showMessageDialog(rootPane, "No existe");
                            System.exit(0);
                        }
                        if (p != 0) {
                            p = 0;
                            res = JOptionPane.showConfirmDialog(rootPane, "¿Es Grande?", null, JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                do {
                                    if (aux.isCazador() && !aux.isPeloLargo() && aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (aux.isCazador() && !aux.isPeloLargo() && aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (aux.isCazador() && !aux.isPeloLargo() && aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            } else {//else não é grande
                                do {
                                    if (aux.isCazador() && !aux.isPeloLargo() && !aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (aux.isCazador() && !aux.isPeloLargo() && !aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (aux.isCazador() && !aux.isPeloLargo() && !aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            }
                        }
                    } else {// else não é caçador
                        do {
                            if (!aux.isCazador() && !aux.isPeloLargo()) {
                                p++;
                            }
                            aux = aux.getSeguiente();
                        } while (aux != null);
                        aux = akita;
                        if (p == 0) {
                            JOptionPane.showMessageDialog(rootPane, "No existe");
                            System.exit(0);
                        }
                        if (p != 0) {
                            p = 0;
                            res = JOptionPane.showConfirmDialog(rootPane, "¿Es Grande?", null, JOptionPane.YES_NO_OPTION);
                            if (res == 0) {
                                do {
                                    if (!aux.isCazador() && !aux.isPeloLargo() && aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (!aux.isCazador() && !aux.isPeloLargo() && aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (!aux.isCazador() && !aux.isPeloLargo() && aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            } else {//else não é grande
                                do {
                                    if (!aux.isCazador() && !aux.isPeloLargo() && !aux.isGrande()) {
                                        p++;
                                    }
                                    aux = aux.getSeguiente();
                                } while (aux != null);
                                aux = akita;
                                if (p == 0) {
                                    JOptionPane.showMessageDialog(rootPane, "No existe");
                                    System.exit(0);
                                }
                                if (p != 0) {
                                    p = 0;
                                    res = JOptionPane.showConfirmDialog(rootPane, "¿Es Deportivo?", null, JOptionPane.YES_NO_OPTION);
                                    if (res == 0) {
                                        do {
                                            if (!aux.isCazador() && !aux.isPeloLargo() && !aux.isGrande() && aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        aux = akita;
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    } else {
                                        do {
                                            if (!aux.isCazador() && !aux.isPeloLargo() && !aux.isGrande() && !aux.isDeportivo()) {
                                                p++;
                                                inicio = aux;
                                            }
                                            aux = aux.getSeguiente();
                                        } while (aux != null);
                                        if (p == 0) {
                                            JOptionPane.showMessageDialog(rootPane, "No existe");
                                            System.exit(0);
                                        }
                                        if (p != 0) {
                                            p = 0;
                                            ImageIcon imagem = new ImageIcon(getClass().getResource(inicio.getRutaImagen()));
                                            JOptionPane.showMessageDialog(null, inicio.getNome(), "Respuesta", JOptionPane.INFORMATION_MESSAGE, imagem);
                                            System.exit(0);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                inicio = inicio.getSeguiente();
            } while (inicio != null);
        }
    }//GEN-LAST:event_jB_PreguntasActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        // TODO add your handling code here:
        if (atual.getAnterior() == null) {
            JOptionPane.showMessageDialog(rootPane, "No tiene movimientos");
        } else {
            atual = atual.getAnterior();
            actualizarInformacion(atual);
        }
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SeguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeguienteActionPerformed
        // TODO add your handling code here:
        if (atual.getSeguiente() == null) {
            JOptionPane.showMessageDialog(rootPane, "No tiene movimientos");
        } else {
            atual = atual.getSeguiente();
            actualizarInformacion(atual);
        }
    }//GEN-LAST:event_SeguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JTextPane Info;
    private javax.swing.JButton Seguiente;
    private javax.swing.JButton jB_Preguntas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jP_Apresentacao;
    private javax.swing.JPanel jP_Comandos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
